controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_logout:
    path: /logout
    methods: GET

app_event:
    path: /event
    controller: App\Controller\EventController::index

app_event_new:
    path: /event/new
    controller: App\Controller\EventController::new

app_admin_event_show:
  path: /admin/event/{id}
  controller: App\Controller\AdminEventController::show